---
title: "Social Media Activists"
author: "Aanchal Setia"
desription: "Initial Ideation of the Research Project"
date: "08/02/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - blog post I
  
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

##BLOG POST I

##Broader Research Interest

I am broadly interested in studying about the social media activism. 
Specifically, I am interested in examining the following questions: 
What type of messages (positively charged emotions vs.
negatively charged emotions) can promote social change? 
Are there any differences in who (activists from disadvantaged groups vs. 
advantaged groups) can express a particular type of message? 

##Literature Review

I have reviewed the following papers that have provided me with insights into
my area of research:

My Fight or Yours: Stereotypes of Activists From Advantaged and Disadvantaged 
Groups (Burrows et al. 2021): 

This paper examines to illustrate the stereotypes that are associated with 
activists across social movements. They hypothesized that activists’ group 
status – whether they are a member of the advantaged group or the 
disadvantaged group – will influence the way activists are perceived in society.
They used qualitative coding to identify the presence of stereotypes that are
used to describe the activists of each group. They found that activists from 
disadvantaged groups are viewed as emotional and reactive, and activists from 
advantaged groups are viewed as altruistic and superficial. 
In my opinion, this was an interesting study, and I would like to examine the
social media content of activists from both groups to see whether their content 
fits the stereotypes listed in this paper.

A sentiment analysis of the Black Lives Matter movement using Twitter 
(Peng et al. 2022): This paper examined public reactions to the BLM movement. 
The researchers used ‘sentiment analysis’ on the Twitter data to explore these 
public reactions. Additionally, they used retweet frequency and word count 
frequency to highlight important sentiments of people towards the BLM movement. 
They found that the BLM movement was received positively as there were a great 
proportion of tweets supporting the movement. The negative sentiment was 
associated with the deaths of black people.  
In my opinion, this was an interesting study understanding multiple 
sentiments revolving around the movement. I want to extend this study 
to measure the differences in the way a social message is received 
dependent on one’s group membership.

##Specific Questions of Interest

	I want to study the tweets of both Black and White activists to highlight 
	the sentiments used to promote social change. I want to compare the emotions 
	of the tweets of Black and White activists on a Black movement and measure
	the conditions that lead to more retweets. Borrowing the stereotypes from 
	Burrows et al. (2022) paper, I want to examine if the content of the social
	media messages of the activists are aligned with the stereotypes attached 
	to their activist identity, and how this alignment or misalignment affects 
	social change (which I would like to measure through retweets). 
	I aim to scrape Twitter data and use techniques 
	(sentiment analysis, word frequency, and retweet frequency) 
	like the Peng et al. (2022) paper.
For now, I am thinking of performing the following research steps:
1.	List the categories from Burrows et al (2022) used to describe activists.
2.	Map these categories to the content found in activists’ tweets.
3.	Additionally, do sentiment analysis on the content of the tweets.
4.	Measure word frequency of categories for Black and White activists’ tweets




