---
title: "Blog Post 1: Literature Review"
author: "Andrea Mah"
desription: "Research question development for DACSS 697D"
date: "09/16/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - hw1
  - challenge1
  - my name
  - dataset
  - ggplot2
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

Literature Review and Research Questions

  Understanding the language used by leaders to discuss important social insight can give us insight into priorities and perspectives of leaders, and how these might vary across different contexts. Further, the ways that leaders talk about issues can guide public opinion. 
  
  Another global challenge that is currently facing us and which requires cooperation across borders is climate change. Serious climate change impacts are occurring or will soon occur, such as increased extreme weather events, forced migration and displacement, and sea level rise (IPCC, 2021). Given these impacts, and the need for widespread efforts to mitigate these impacts through reductions in GHG emissions, understanding how world leaders think about climate change could be useful to make sense of responses. One forum where many leaders gather to discuss these issues are the United Nations Climate Change conference, which serve as the Conference of Parties (COP) conventions.
  
  These annual conferences began in 1995, three years after numerous countries had joined the United Nations Framework Convention on Climate Change (UNFCC, retrieved Sep 2022). These meetings bring together world leaders to assess the state of affairs of climate change, and to make decisions that will encourage or enforce climate change mitigation and adaptation efforts. In 1997, the conference resulted in adoption of the Kyoto Protocol which was developed as a way for countries to commit to various goals aimed at mitigation of climate change through agreed upon limits on GHG emissions. The Kyoto Protocol first went into effect in 2008. In 2015, the COP adopted the Paris Agreement, which was intended to have countries agree to stricter limits and more drastic actions to prevent global warming greater than 2 degrees Celsius. The attendees of these meetings include governmental representatives from the 200+ countries that are party to the convention, along with 'observers' who are representatives of intergovernmental organizations and non-governmental organizations. During the proceedings, negotiations over targets and timelines are made over the course of two weeks. Outcomes of the conferences include agreements on targets/limits, guidelines for assessment and reporting of progress, and decisions on how funds should be allocated. 
  
  Past work has used computational and non computational methods to examine media and public responses to COP conferences (e.g., Esparcia & Gomez, 2021; Chen & Jia, 2022; ). For example, Esparcia & Gomez (2021) analyzed features of journalistic content from american media outlets that publish news with some form of polarization. They identified differences between these types of sources in reporting on COP25, with right-leaning sources being more likely to publish articles framed around denial (e.g., attempts at discrediting climate scientists). Left-leaning publications were less likely to publish stories on the climate strikes which occurred, and were more likely than right-leaning publications to include news about fossil and energy industries or climate change impacts (Esparcia & Gomez, 2021). In work comparing media responses in China and the U.S., Chen & Jia (2022) conducted lexical and discourse analysis of news articles published about COP26. They found that U.S. articles more frequently included direct quotations as compared with Chinese news media who tend to use more indirect or partial statements. Further, U.S. articles were more likely than Chinese articles to include mention of President Xi Jingping, and that this was often in the context of mentioning his absence from the conference. Another study which used content analysis of journalist's tweets from COP25 calculated engagement with tweets in relation to the tweet's content and author, finding that tweets with negative sentiments, which contained only text, or which were from journalists tended to garner the greatest engagement (Polaino et al., 2021). 
  
  Another way that these COP meetings have been studied is through analysis of speeches given during the conferences. Ahmed(2022) analyzed the types of metaphors used in speeches given by African and European leaders at COP26 through qualitative analysis of 10 speeches from each continent. Through this analysis, Ahmed discovered some differences in propensity to use certain types of metaphors among European and African leaders. While European leaders spoke about climate change as a war/conflict, a stock market, and doomsday, African leaders spoke about how facing climate change is a journey, how nature is human, and how dealing with climate change is building a project. In other contexts, speeches made by leaders have been analyzed for different types of information and comparisons. For example, one analysis of speeches made by leaders during the pandemic revealed common themes discussed across countries, such as discussion of the economy, but variation was also observed, for example in gender differences of the frequency of discussion of social welfare and vulnerable populations (Dada et al., 2021). However, these studies were limited in the number of speeches that they analyzed, likely because they used human-powered approaches to analyzing these speeches.
  
   In the current project, I aim to study how the lexicon of speeches and statements delivered at COP conferences has shifted over time and varies by features of the speaker (e.g., nationality, role, demographics...). Speeches, statements, and other forms of documents are available at the UNFCC website archives. These are published in pdf formats, and there are ~500 published speeches that I saw at first search attempts. Some potential topics I'd like to explore include: 
  
 -"climate change vs. global warming": Over time, there have been shifts in the language used by scientists, media, and the public to discuss climate change (e.g., use of global warming -> climate change -> climate emergency/crisis). 
 
 -"mitigation vs. adaptation":  I want to examine whether there has been a shift in terms relating to mitigation vs. adaptation. Although initial COP conferences were heavily focused on setting targets for reduced carbon emissions (i.e., mitigation), there is a growing recognition of the need for adaptation to climate impacts, as these are already occurring. On the other hand, I might expect there to be less discussion of adaptation because while mitigation requires global cooperation, many adaptation efforts are carried out at local levels (and must be due to geographical variation in climate impacts) 
 
 -"resilience": I am also interested in whether 'resilience' as a concept has changed in popularity over time, or if it is favored by certain countries but not others. 
 
 -"denial/skepticism vs. science": I am also interested in whether there is discussion of climate skepticism or denial and if so, how much these ideas are emphasized (i.e., the need to address public skepticism of climate science). There has also been a history of the COP meetings and more generally the UNFCC being criticized for not listening to scientists, although that has changed in recent years as more input from the IPCC has been integrated into proceedings.
 
 -"hope" and other emotions: are world leaders discussing climate change using personal, emotional language or experiences? How much is the concept of "hope" discussed
 
 -"technosalvation": one of the psychological barriers to climate action (Gifford, 2011) is the idea that we can be saved by technology. How much is technology discussed as the solution to climate change in the context of COP speeches?
 
 -top-down vs. bottom-up: there is a debate in how climate change should be addressed: through individual (bottom-up) action or through the implementation of policies/regulations from the top-down. By its nature, the convening of the UNFCC represents bringing together leaders who have the potential power to implement top-down changes, but I wonder if there is discussion of the need for individual behavior change? 
 
 References:
 Ahmed, M. M. (2022). Conceptual Metaphors in Climate Change Discourse in the Speeches of African Vs. European Political Leaders: A Cognitive Approach. Transcultural Journal of Humanities and Social Sciences, 3(2), 17–30. https://doi.org/10.21608/tjhss.2022.233093
 Polaino, R., Mera Fernández, M., & Parratt Fernández, S. (2022). Journalists and Engagement on Twitter and Climate Change: Tweet Authors, Formats, and Content During COP25. Journalism Practice, 16(2–3), 486–501. https://doi.org/10.1080/17512786.2021.1981151
Castillo Esparcia, A., & López Gómez, S. (2021). Public Opinion about Climate Change in United States, Partisan View and Media Coverage of the 2019 United Nations Climate Change Conference (COP 25) in Madrid. Sustainability, 13(7), 3926. https://doi.org/10.3390/su13073926
Chen, Y., & Jia, H. (2022). A corpus-based critical discourse analysis of COP 26 in Chinese and Western Media. Proceedings of the 5th International Conference on Big Data and Education, 379–386. https://doi.org/10.1145/3524383.3524418
Dada, S., Ashworth, H. C., Bewa, M. J., & Dhatt, R. (2021). Words matter: Political and gender analysis of speeches made by heads of government during the COVID-19 pandemic. BMJ Global Health, 6(1), e003910. https://doi.org/10.1136/bmjgh-2020-003910
Gifford, R. (2011). The dragons of inaction: Psychological barriers that limit climate change mitigation and adaptation. American Psychologist, 66, 290–302. https://doi.org/10.1037/a0023566
IPCC, 2021: Climate Change 2021: The Physical Science Basis. Contribution of Working Group I to the Sixth Assessment Report of the Intergovernmental Panel on Climate Change [Masson-Delmotte, V., P. Zhai, A. Pirani, S.L. Connors, C. Péan, S. Berger, N. Caud, Y. Chen, L. Goldfarb, M.I. Gomis, M. Huang, K. Leitzell, E. Lonnoy, J.B.R. Matthews, T.K. Maycock, T. Waterfield, O. Yelekçi, R. Yu, and B. Zhou (eds.)]. Cambridge University Press, Cambridge, United Kingdom and New York, NY, USA, 2391 pp. doi:10.1017/9781009157896

 