---
title: "Blog Post 1"
author: "Nayan Jani"
description: "Literature Review"
date: "09/19/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - Blog
  - mental_health
  
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)

knitr::opts_chunk$set(echo = TRUE)
```

## Instructions

The topic I want to explore is mental health data. Based on my search for scholary articles, I have decided to look at mental health treatments across adults in america and Covid-19 and suicide data across Massachusetts.


## Mental Health Treatment Among Adults: United States

This article comes from the CDC's website under the National Center for Health Statistics section for mental health. The main research questions include: What percentage of adults have received any mental health treatment varied by age group, are men or women more likely to receive mental health treatments, does the percentage of adults who had received any mental health treatment vary by urbanization level and  what percentage of a demographic received the highest amount of mental health treatments. Data from the 2019 NHIS (National Health Interview Survey) were used for this analysis in this article .NHIS is a nationally representative household survey of the U.S. civilian noninstitutionalized population. The NHIS, conducted by NCHS, is the major source for high-quality data used to monitor the nation’s health. Methods that were used to evaluate the trends of adult mental health treatments were  orthogonal polynomials in logistic regression. Important findings include as follows: 19.2% of adults had received any mental health treatment in the past 12 months, Women were more likely than men to have received any mental health treatment,  Non-Hispanic white adults (23.0%) were more likely than non-Hispanic black (13.6%) and Hispanic (12.9%) adults to have received any mental health treatment and  as the level of urbanization decreased, the percentage of adults who had taken medication for their mental health increased. After reviewing this article I believe that using survey data that is based on mental health would be a interesting project because there are tons of relationship between different groups of people and some group are at a higher risk than others to develop mental health issues. This article only looks at a few relationships such as location, ethnicity and age so there is many other relationships to explore such as gender, wealth, race etc. 


## COVID-19 Data Brief 2020: Suicides, Suicide Attempts and Suicidal Ideation in Massachusetts

This article comes from Mass.gov archive of public health data. It focuses on Suicidiality before and after Covid-19 became prevalent in our lives. Some of topics include: Emergency department visit trends from Jan 2018 to May 2021, Suicidal Ideation and Suicide Attempts of different genders from Jan 2018 to May 2021 and Suicide death trends by month. The data comes from the Massachusetts Syndromic Surveillance Program. The Massachusetts Syndromic Surveillance Program has been collecting data from 100% of emergency department (ED) visits within the state of Massachussetts and real time data is transmitted from ED facilities. From this article, the findings that stuck out to me are as follows:

- Between January and April of 2020, total monthly ED visits declined 50%, ED visits for suicidal ideation declined 34%, and ED visits for suicide attempts declined 28%
- Since April 2020, ED visits across all three syndromes have risen (all reasons for admittance, suicide attempt and ideation) 
- females under age 25 saw the largest relative increase in ED visits related to suicide since the start of the pandemic
- Between March and December of 2020, Massachusetts averaged 51 suicide deaths per month, indicating that suicide deaths continued to decline despite an increase in overall poor mental health during the COVID-19 pandemic.
- Nationally, suicide rates declined by 2.1% in 2019, but Massachusetts was one of only five states to see a statistically significant decline in suicides between 2018 and 2019

Based on these findings, I can see that the pandemic negatively effected the treatment of any suicide symptoms because people could not or stopped trying to get treatment. Total monthly treatments are down since before the pandemic started which suggests that people are not feeling the need for emergency visits when they still may need them. Mass has done a great job reducing its state level suicide rate but I feel that will increase as time goes on. I would love to do a similar study but for mental health in general.



## My Research questions

What I want to do for my project is to answer similar questions that have be drawn in these articles but more oriented on the demo and psycho graphics of different groups of people that are effected by mental health disorders. I also want to look into which groups of people are at most risk for mental health issues and where in the USA are the most mentally unhealthy people reside. The dataset I want to use is the Massachusetts Behavioral Risk Factor Surveillance
Survey data. The BRFSS is an annual telephone survey that collects information on the health issues and risk factors of adults across the state. More specifically, it is a continuous, state-based surveillance system that collects information about modifiable risk factors for chronic diseases and other leading causes of death. 

## Links to articles and Data

<https://www.cdc.gov/nchs/data/databriefs/db380-H.pdf>

<https://www.mass.gov/info-details/suicide-data-reports#2020-data-> 2020 data

<https://chronicdata.cdc.gov/Behavioral-Risk-Factors/Behavioral-Risk-Factor-Surveillance-System-BRFSS-P/dttw-5yxu/data>


