---
title: "Blog Post One - Exploring Healthcare Costs"
author: "Rhowena Vespa"
desription: "Initial Research on Healthcare Costs"
date: "09/18/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - hw1
  - my name
  - dataset
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)


```



## What are research questions?
The research aims to understand the effects of financial cost on decisions affecting access to healthcare services. Specifically, the study looks on health-related financial uncertainty and how patients view access to medications as cost prohibitive. It also studied perceptions of health systems and specialty pharmacies.
What data are used? 

TrellisRx did not disclose raw interview data. For Romo, LK et al study, I have requested UMass for access to full article. Currently, I only have the abstract information.


## How are the data collected? What methods are used?
Data was collected through 17 participants using semi-structured data interviews for Romo, LK et. al 
TrellisRx had 20 participants involving established health plans and hospital administrators and it used blinded and unblinded expert interviews, and blinded interview participants.
What are the findings of the study?
Romo, LK study found significant negative effects on physical and mental issues, such as depression, on participants with health-related financial uncertainty. Participants worried about the cost of seeking care and the financial burden of receiving such care.  This study found that effective communication to participants help manage this financial uncertainty, including sharing information, social networking and establishing emotional support.
TrellisRx found numerous misperceptions between health systems and health payors. This is especially useful in finding common ground between these two systems. The studies found that both parties have a common objective of improving health outcomes and ensuring patient access and affordability to access quality care. It is very interesting that both parties have a lot of common ground, including an agreement that the rising cost of drugs in unsustainable. 


## What's your take on it?
It is common knowledge that the complex US healthcare system needs to improve. The financial burden of accessing healthcare is creating a toll on an individual’s physical and mental health. 
More research questions:

          1.	How do patients perceive access to specialty health care, including specialty medicines?
          2.	How do prescribers and health systems perceive patient’s ability to access healthcare?
          3.	How to quantify health disparities on specialty care? 
          4.	What factors would patients consider in accessing specialty care?
          5.	How can providers help break down barriers to improve health equity?

## REFERENCES:

          1. Lynsey K. Romo, Charee Mooney Thompson & Patience Ben-Israel (2022) An Examination of How People Appraise and Manage Health-Related Financial Uncertainty, Health Communication, 37:8, 935-943, DOI: 10.1080/10410236.2021.1876813
          2. Specialty Pharmacy Insights: Aligning Health Systems and health plans for better patient-centered care. Trellis Rx. https://www.trellisrx.com/resources/specialty-pharmacy-research/. Published May 27, 2020. Accessed September 18, 2022. 


