---
title: "Fake Challenge"
author: "Rhowena Vespa"
desription: "Data Visualization of Health Outcomes"
date: "09/16/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
    - ggplot2
---

```{r}
#| label: setup
#| warning: false

library(tidyverse)
library(ggplot2)
library(readxl)


```


```{r}
#| label: setup
#| warning: false

library(tidyverse)
library(dplyr)
library(ggplot2)
fake <-read_excel('C:/Users/Owen/Documents/PLACES__Local_Data_for_Better_Health__County_Data_2021_release.xlsx')
```


```{r}
ggplot(fake, aes(x = MeasureId , y= Data_Value)) +
  geom_bar(position="dodge",stat = "identity") +
  labs(x = "Health Identifiers",
       y = "Percent of Population",
       title = "Percentage of Health identifiers") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size=8),
        axis.text.y = element_text(size=12),
        axis.title.y = element_text(size=12),
        axis.title.x = element_text(size=12),
        plot.title = element_text(size=12,hjust=0.5))
```

## Reference:

Places: Local data for Better Health, county data 2021 release. Centers for Disease Control and Prevention. https://chronicdata.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-County-Data-20/swc5-untb. Accessed September 18, 2022. 

