---
title: "Blog Post 1"
author: "Miranda Manka"
desription: "Literature Review & Developing Research Ideas and Questions"
date: "09/18/2022"
format:
  html:
    toc: true
    code-fold: true
    code-copy: true
    code-tools: true
categories:
  - blog posts
---

## Literature Review
Find two academic articles that address topics of your interest and utilize quantitative and/or computational analysis of text.

## Article 1
- Topic modeling and sentiment analysis of global climate change tweets by Biraj Dahal, Sathish A. P. Kumar, and Zhenlong Li
(https://www.researchgate.net/profile/Sathish-Kumar-26/publication/331453828_Spatiotemporal_Topic_Modeling_and_Sentiment_Analysis_of_Global_Climate_Change_Tweets/links/5d9033e6a6fdcc2554a4740e/Spatiotemporal-Topic-Modeling-and-Sentiment-Analysis-of-Global-Climate-Change-Tweets.pdf)

### What are the research questions and/or hypothesis? 
- The goal of this study is to perform volume analysis, sentiment analysis, and topic modeling to a collection of tweets and compare these results over space and time.

### What data are used and how are the data collected?
- The dataset consists of 390,016 tweets from July 1, 2016, to February 28, 2018, collected using the Twitter Stream Application Programming Interface (API).
- This dataset consists of geotagged tweets posted in that period that contained at least one of the following keywords or some variant of them: climate change, carbon dioxide, fossil fuel, carbon footprint, emissions.
- Each geotagged tweet has a longitude and latitude pair associated with the location the user was in when the tweet was posted. The data for each tweet have the following relevant variables: tweetid (the unique code given to the tweet), userid (the Twitter code of the user that posted that tweet), postdate (the time and day the tweet was posted), latitude, longitude, and message (the body of the tweet).

### What methods are used? 
- Volume analysis and text mining techniques such as topic modeling and sentiment analysis
- Latent Dirichlet allocation was applied for topic modeling to infer the different topics
of discussion, and Valence Aware Dictionary and sEntiment Reasoner was applied for sentiment analysis to determine the overall feelings and attitudes found in the dataset.

### What are the findings of the study? 
- Sentiment analysis shows that the overall discussion is negative, especially when users are reacting to political or extreme weather events. Topic modeling shows that the different topics of discussion on climate change are diverse, but some topics are more prevalent than others. In particular, the discussion of climate change in the USA is less focused on policy-related topics than other countries.

### What's your take on it?
-I thought this article/study was really interesting to read. There were a lot of analyses and graphs for things I hadn't even thought of before reading it. I thought the differences over time and that the overall discussion of climate change on Twitter is negative were some interesting points. Overall, I think this is a really good article that can be helpful to look back at.

## Article 2
- How Climate Movement Actors and News Media Frame Climate Change and Strike: Evidence from Analyzing Twitter and News Media Discourse from 2018 to 2021 by Kaiping Chen, Amanda L. Molder, Zening Duan, Shelley Boulianne, Christopher Eckart, Prince Mallari, and Diyi Yang
(https://journals-sagepub-com.silk.library.umass.edu/doi/pdf/10.1177/19401612221106405)

### What are the research questions and/or hypothesis?
- RQ1: How is climate strike discourse framed on Twitter and how has this discourse evolved over time?
- RQ2: How do the two different groups, climate movement actors and mainstream news media frame the climate movement differently?
- RQ3: Who are the targeted entities in the climate strike discourse on Twitter?
- RQ4: How do targeted entities differ between social movement actors on Twitter
and mainstream news media?

### What data are used and how are the data collected?
- Five million English tweets posted from 2018 to 2021 demonstrating how peaks in Twitter activity relate to key events and how the framing of the climate strike discourse has evolved over the past three years. Collected over 30,000 news articles from major news sources in English-speaking countries.
- For RQ1 - They developed 33 hashtags related to climate strike. Then, they used a third-party data platform Synthesio to collect English tweets, if the tweet contained at least one preselected hashtag and were posted by US users from August 2018 to January 2021, Synthesio returns data with content-level information such as the tweet content, user-level information such as the Twitter handle and the geolocation information of a user, and the time stamp.
- For RQ2 - They filtered their Twitter dataset, compiled a list of climate movement actor Twitter handles and filtered the US Twitter discourse dataset to select all tweets that were posted by actors based in the US. The search terms they used to collect news stories from the Media Cloud are climate change, global warming, climate emergency, climate crisis, climate strike, climate protest, and climate march. Media Cloud gathered digital presence (URLs) of these news outlets and then they applied a third-party scraper Zyte to parse all URLs. They chose the news outlets from each respective country according to the source from the Digital News Report 2020 (Newman et al. 2020) as having the highest market share (e.g., weekly usage). In total, 30,669 news stories were included and used for analyses.

### What methods are used? 
- Topic modelling to Identify Major Frames of Climate Strike and Their Evolution (unsupervised topic model algorithm Latent Dirichlet Allocation)
- The resulting models are compared based on model diagnostics such as coherence score
- NLP to Identify Major Entities in Climate Strike Discourse

### What are the findings of the study? 
- News outlets tend to report on global politicians’ (in)action toward climate policy, the consequences of climate change, and industry’s response to the climate crisis. Differently, climate movement actors on Twitter advocate for political actions and policy changes as well as addressing the social justice issues surrounding climate change.
- Conversations around the climate movement on Twitter are highly politicized, with a substantial number of tweets targeting politicians, partisans, and country actors. These findings contribute to our understanding of how people use social media to frame political issues and collective action, in comparison to the traditional mainstream news outlets.

### What's your take on it?
- I thought this paper had a relatively extensive analysis into the comparisons for the research questions presented. This article gives me a lot to think about with designing my own questions, as well as providing more data collection and analysis methods. I thought the conclusions about news outlets and on twitter were both interesting.

## Based on this brief navigation, discuss your own research questions and potential data sources.
- By looking at some of the similarities between the papers, I have some ideas about my own, although I am still very unsure. 
- I think getting data from twitter may be my best option, but I will sill be looking for the best tools to use.
- I like the idea of looking at certain climate keywords to focus on and narrow down the search.
- Maybe use sentiment analysis on tweets in English, but narrow down by country.
- Try to determine if tweets are about policy or not, or about weather, politics, etc.
- I am still unsure on the specific direction to take.

## At this phase you might have more questions than answers. Document all those questions.
- What is the best tool/software to use to get my data?
- What is the best place to even get the data from (probably twitter)?
- How much data do I need?
- How do I narrow down exactly what I want to analyze?
- If I use keywords, which ones?
- How specific does it need to be?
- How long should the analysis be?

### Bibliography
Chen, Kaiping, et al. “How Climate Movement Actors and News Media Frame Climate Change and Strike: Evidence from Analyzing Twitter and News Media Discourse from 2018 to 2021.” The International Journal of Press/Politics, 19 June 2022, https://doi.org/10.1177/19401612221106405. 
Dahal, Biraj, et al. “Topic Modeling and Sentiment Analysis of Global Climate Change Tweets.” Social Network Analysis and Mining, 10 June 2019, https://doi.org/10.1007/s13278-019-0568-8. 

