---
title: "Post 1"
author: "Saaradhaa M"
description: "Introduction to Research Topic: Cross-Cultural Psychology"
date: "09/18/2022"
editor: visual
format:
  html:
    df-print: paged
    toc: true
    code-copy: true
    code-tools: true
    css: "styles.css"
categories:
  - post 1
---

```{r}
#| label: setup
#| warning: false
#| message: false
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Research Question

As someone from a non-WEIRD country, one of my interests is cross-cultural psychology. I would like to gain a better understanding of less explored cultures and go beyond the traditional East/West dichotomy that much of the literature focuses on. Broadly, my research questions are as follows (thesecan be refined as the semester progresses):

::: callout-tip
1.  How can we use text data to analyse the differences between honour, dignity and face cultures?

2.  What are the common values that can be extracted from cross-cultural texts? What does this reveal about "global" values that transcend cultural distinctions?
:::

## Leung & Cohen (2011)

Leung and Cohen argue for the existence of three cultural types -- honour, dignity and face -- and test this out with two experiments. They hypothesize these three cultural types based on distinct cultural norms.

They propose three "perfect" descriptions for each cultural type, while acknowledging that some societies may be a combination of the types.

These were my key takeaways about each type:

1.  Dignity: Everybody has individual worth that is not taken away by others' worth. People tend to be internally driven and law-abiding.

2.  Honour: People care about how they value themselves, but also how they are valued by society. Themes of tit-for-tat are common.

3.  Face: Protecting your reputation (as perceived by others) is most important, and social systems are hierarchical. Your face is not taken away by others', so it is beneficial to collaborate in protecting everyone's face.

Participants were white Americans from northern US (dignity), white Americans from southern US and Latinos (honour) and Asian Americans (face). Experiment 1 tested their patterns of reciprocal behaviour, perceptions of worth (external vs. internal) and alignment with honour-related aggression. Experiment 2 extended Experiment 1 by also testing truthfulness and the importance of face. Findings indicated distinct profiles for the three cultural types based on the tested dimensions.

*My thoughts: A lot of theoretical details were presented in an abstract manner that made this paper challenging to follow. However, the way they operationalised their argument was fascinating and has led to lots of interesting research in this area.*

## Wilkerson & Casas (2017)

This was one of our assigned readings for this week, but it ended up being useful for my post. Before describing their own study, they first provide a useful summary of the stages of quantitative text analysis: how to obtain your data, transform it to quantitative data, analyse it (through both statistical and text analysis methods) and validate it. They describe new methods in the field, such as unsupervised learning to explore datasets and sentiment analysis.

After mentioning some challenges in topic modelling (e.g., no ideal method of validation, topics unstable across iterations), they provide their own example of using topic modelling to uncover common topics in \>9,000 US government speeches, and whether these differ between the Democratic and Republican parties.

They briefly describe how they pre-processed the data and transformed it into a quantitative format (1 row = 1 speech, 1 column = presence of 1 feature/word). They made 17 versions of topic models with 850 topics, then used cosine similarities to uncover the most common topics. These were then grouped into broader topic categories called meta-topics. 1 metatopic that they were unable to interpret clearly was excluded. For their analysis, "more clusters improve(d) overall fit until approximately 50 clusters" (Wilkerson & Casas, 2017, p. 538).

They then mention steps taken to ensure that the speeches within each topic model conform to it -- *I am unsure if this was done manually/automatically, and do not fully understand this portion. Could we go over it in class?*

By working through the exercise above, they propose "similarity of estimates of topic emphasis across different models" (Wilkers & Casas, 2017, p. 539) as a good way to validate topic modelling.

*My thoughts: This paper was harder to read than the first one, given my unfamiliarity with topic modelling. I hope that as we discuss more text analytic methods in class, I will have a better understanding of this paper and how I can employ similar methods to extract topics from corpora.*

## Potential Data Sources

-   Presidential speeches from [Japan](https://japan.kantei.go.jp/97_abe/statement/201601/index.html) (face), [India](https://presidentofindia.nic.in/speeches.htm) (honour) and [US](https://millercenter.org/the-presidency/presidential-speeches) (dignity). These might be good examples of wider cultural norms.

    -   In combination with this, I could also use the [Reddit API](https://www.reddit.com/dev/api) to gather posts and comments from r/japan, r/india and r/california (there seems to be no good "USA" subreddit, so I chose the most populous state instead). This would allow us to examine differences between **presidential vs. popular representations of these 3 cultures**.

-   Analyzing movie scripts from [US](https://imsdb.com/) (dignity), [India](https://www.filmcompanion.in/category/fc-pro/scripts/) (honour) and [Japan](https://transcripts.foreverdreaming.org/) (face).

    -   Dr. Song highlighted that one issue with analyzing mass media might be copyright laws. I believe that use of copyrighted material for strictly non-profit, educational purposes would be acceptable, but hope we can further discuss this in class.

    -   Examples of research articles using movie scripts for analysis: [1](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7256373/) (US movies), [2](http://proceedings.mlr.press/v81/madaan18a/madaan18a.pdf) (Indian movies), [3](https://journals.sagepub.com/doi/pdf/10.1177/1367006910379300?casa_token=ctzZLB598loAAAAA:-xAQ16o8is7J-9pcWUD6FtN5urx6o4xics4WSMcP7Kr52SiCg34uoXamHs4oJKTRGHv-g_RBj6-p6w) (Indian movies).

-   Analysing oral histories from East Asian Americans (face), South Asian Americans (honor) and European Americans (dignity). *The first two are available on the UCLA Oral History website, but I've yet to come across a good resource for European Americans. This dataset might also be too small.*

## Other questions I have:

-   *Is topic modelling a good way to explore the data? Are there other ways of analyzing themes/values that I should look into (e.g., text networks)?*

-   *If I come across content in other languages and translate it into English, how much "meaning" is lost in translation? Who are some good authors in the literature to learn from?*

## Bibliography

Leung, A., & Cohen, D. (2011). Within- and between-culture variation: Individual differences and the cultural logics of honor, face, and dignity cultures. Journal Of Personality And Social Psychology, 100(3), 507-526.

Wilkerson, J., & Casas, A. (2017). Large-Scale Computerized Text Analysis in Political Science: Opportunities and Challenges. Annual Review Of Political Science, 20(1), 529-544.
